var temperature_data = [
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2015-01",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "8",
        "EMNT_ATTRIBUTES": ",W,08,",
        "EMXT": "55",
        "EMXT_ATTRIBUTES": ",W,04,",
        "HDSD": "2590",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "30.8",
        "TMAX": "37.3",
        "TMIN": "24.2"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2015-02",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "3",
        "EMNT_ATTRIBUTES": ",W,20,",
        "EMXT": "43",
        "EMXT_ATTRIBUTES": ",W,22,",
        "HDSD": "3720",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "24.7",
        "TMAX": "32.7",
        "TMIN": "16.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2015-03",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "13",
        "EMNT_ATTRIBUTES": ",W,06,",
        "EMXT": "62",
        "EMXT_ATTRIBUTES": ",W,11,",
        "HDSD": "4562",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "37.8",
        "TMAX": "45.3",
        "TMIN": "30.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2015-04",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "33",
        "EMNT_ATTRIBUTES": ",W,02,",
        "EMXT": "77",
        "EMXT_ATTRIBUTES": ",W,29,",
        "HDSD": "4934",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "52.6",
        "TMAX": "61",
        "TMIN": "44.2"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2015-05",
        "CDSD": "58",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "43",
        "EMNT_ATTRIBUTES": ",W,02,",
        "EMXT": "87",
        "EMXT_ATTRIBUTES": ",W,12,",
        "HDSD": "5015",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "64.2",
        "TMAX": "72.9",
        "TMIN": "55.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2015-06",
        "CDSD": "276",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "51",
        "EMNT_ATTRIBUTES": ",W,02,",
        "EMXT": "90",
        "EMXT_ATTRIBUTES": ",W,21,",
        "HDSD": "5046",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "71.2",
        "TMAX": "78.5",
        "TMIN": "63.9"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2015-07",
        "CDSD": "691",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "65",
        "EMNT_ATTRIBUTES": ",W,03,",
        "EMXT": "95",
        "EMXT_ATTRIBUTES": ",W,29,+",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "78.4",
        "TMAX": "85.2",
        "TMIN": "71.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2015-08",
        "CDSD": "1109",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "64",
        "EMNT_ATTRIBUTES": ",W,28,",
        "EMXT": "92",
        "EMXT_ATTRIBUTES": ",W,04,",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "78.5",
        "TMAX": "86.3",
        "TMIN": "70.7"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2015-09",
        "CDSD": "1350",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "56",
        "EMNT_ATTRIBUTES": ",W,27,",
        "EMXT": "93",
        "EMXT_ATTRIBUTES": ",W,03,",
        "HDSD": "1",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "73",
        "TMAX": "81",
        "TMIN": "65"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2015-10",
        "CDSD": "1356",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "36",
        "EMNT_ATTRIBUTES": ",W,19,",
        "EMXT": "74",
        "EMXT_ATTRIBUTES": ",W,29,+",
        "HDSD": "230",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "57.8",
        "TMAX": "65.4",
        "TMIN": "50.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2015-11",
        "CDSD": "1360",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "31",
        "EMNT_ATTRIBUTES": ",W,24,",
        "EMXT": "75",
        "EMXT_ATTRIBUTES": ",W,06,",
        "HDSD": "607",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "52.6",
        "TMAX": "60.2",
        "TMIN": "44.9"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2015-12",
        "CDSD": "1360",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "34",
        "EMNT_ATTRIBUTES": ",W,29,+",
        "EMXT": "70",
        "EMXT_ATTRIBUTES": ",W,13,",
        "HDSD": "1062",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "50.3",
        "TMAX": "56.4",
        "TMIN": "44.2"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2016-01",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "12",
        "EMNT_ATTRIBUTES": ",W,05,",
        "EMXT": "58",
        "EMXT_ATTRIBUTES": ",W,10,",
        "HDSD": "2004",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "34.6",
        "TMAX": "41.5",
        "TMIN": "27.7"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2016-02",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "1",
        "EMNT_ATTRIBUTES": ",W,14,",
        "EMXT": "62",
        "EMXT_ATTRIBUTES": ",W,29,",
        "HDSD": "2797",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "37.7",
        "TMAX": "45.1",
        "TMIN": "30.1"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2016-03",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "27",
        "EMNT_ATTRIBUTES": ",W,03,",
        "EMXT": "72",
        "EMXT_ATTRIBUTES": ",W,23,",
        "HDSD": "3339",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "47.5",
        "TMAX": "55.3",
        "TMIN": "39.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2016-04",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "26",
        "EMNT_ATTRIBUTES": ",W,05,",
        "EMXT": "78",
        "EMXT_ATTRIBUTES": ",W,18,",
        "HDSD": "3758",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "51",
        "TMAX": "59.4",
        "TMIN": "42.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2016-05",
        "CDSD": "49",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "44",
        "EMNT_ATTRIBUTES": ",W,16,",
        "EMXT": "87",
        "EMXT_ATTRIBUTES": ",W,25,",
        "HDSD": "3954",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "60.3",
        "TMAX": "67.7",
        "TMIN": "52.8"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2016-06",
        "CDSD": "259",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "54",
        "EMNT_ATTRIBUTES": ",W,08,",
        "EMXT": "92",
        "EMXT_ATTRIBUTES": ",W,22,",
        "HDSD": "3958",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "71.9",
        "TMAX": "80.1",
        "TMIN": "63.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2016-07",
        "CDSD": "679",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "66",
        "EMNT_ATTRIBUTES": ",W,12,+",
        "EMXT": "98",
        "EMXT_ATTRIBUTES": ",W,23,",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "78.6",
        "TMAX": "85.7",
        "TMIN": "71.4"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2016-08",
        "CDSD": "1111",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "64",
        "EMNT_ATTRIBUTES": ",W,23,+",
        "EMXT": "95",
        "EMXT_ATTRIBUTES": ",W,14,",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "78.9",
        "TMAX": "85.4",
        "TMIN": "72.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2016-09",
        "CDSD": "1309",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "51",
        "EMNT_ATTRIBUTES": ",W,26,",
        "EMXT": "91",
        "EMXT_ATTRIBUTES": ",W,09,",
        "HDSD": "15",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "71.1",
        "TMAX": "77.9",
        "TMIN": "64.2"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2016-10",
        "CDSD": "1327",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "39",
        "EMNT_ATTRIBUTES": ",W,29,",
        "EMXT": "86",
        "EMXT_ATTRIBUTES": ",W,19,",
        "HDSD": "222",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "58.9",
        "TMAX": "66.8",
        "TMIN": "51.1"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2016-11",
        "CDSD": "1327",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "36",
        "EMNT_ATTRIBUTES": ",W,23,",
        "EMXT": "73",
        "EMXT_ATTRIBUTES": ",W,03,",
        "HDSD": "654",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "50.6",
        "TMAX": "57.8",
        "TMIN": "43.4"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2016-12",
        "CDSD": "1327",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "19",
        "EMNT_ATTRIBUTES": ",W,16,",
        "EMXT": "62",
        "EMXT_ATTRIBUTES": ",W,27,",
        "HDSD": "1441",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "39.6",
        "TMAX": "45.7",
        "TMIN": "33.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2017-01",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "13",
        "EMNT_ATTRIBUTES": ",W,09,",
        "EMXT": "61",
        "EMXT_ATTRIBUTES": ",W,12,",
        "HDSD": "2259",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "38.6",
        "TMAX": "43.9",
        "TMIN": "33.4"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2017-02",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "19",
        "EMNT_ATTRIBUTES": ",W,09,",
        "EMXT": "68",
        "EMXT_ATTRIBUTES": ",W,19,",
        "HDSD": "2948",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "40.4",
        "TMAX": "47.8",
        "TMIN": "33"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2017-03",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "16",
        "EMNT_ATTRIBUTES": ",W,05,",
        "EMXT": "64",
        "EMXT_ATTRIBUTES": ",W,09,",
        "HDSD": "3743",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "39.4",
        "TMAX": "46.9",
        "TMIN": "31.8"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2017-04",
        "CDSD": "11",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "38",
        "EMNT_ATTRIBUTES": ",W,01,",
        "EMXT": "85",
        "EMXT_ATTRIBUTES": ",W,29,",
        "HDSD": "4052",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "55.1",
        "TMAX": "62.7",
        "TMIN": "47.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2017-05",
        "CDSD": "48",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "42",
        "EMNT_ATTRIBUTES": ",W,08,",
        "EMXT": "92",
        "EMXT_ATTRIBUTES": ",W,19,",
        "HDSD": "4228",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "60.5",
        "TMAX": "67.4",
        "TMIN": "53.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2017-06",
        "CDSD": "246",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "51",
        "EMNT_ATTRIBUTES": ",W,09,",
        "EMXT": "94",
        "EMXT_ATTRIBUTES": ",W,13,",
        "HDSD": "4250",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "70.9",
        "TMAX": "78.7",
        "TMIN": "63.1"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2017-07",
        "CDSD": "601",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "62",
        "EMNT_ATTRIBUTES": ",W,30,",
        "EMXT": "95",
        "EMXT_ATTRIBUTES": ",W,21,",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "76.4",
        "TMAX": "83.6",
        "TMIN": "69.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2017-08",
        "CDSD": "899",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "60",
        "EMNT_ATTRIBUTES": ",W,30,+",
        "EMXT": "88",
        "EMXT_ATTRIBUTES": ",W,16,+",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "74.6",
        "TMAX": "81.9",
        "TMIN": "67.4"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2017-09",
        "CDSD": "1079",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "54",
        "EMNT_ATTRIBUTES": ",W,30,+",
        "EMXT": "92",
        "EMXT_ATTRIBUTES": ",W,24,",
        "HDSD": "13",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "70.5",
        "TMAX": "78.2",
        "TMIN": "62.9"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2017-10",
        "CDSD": "1141",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "42",
        "EMNT_ATTRIBUTES": ",W,17,",
        "EMXT": "84",
        "EMXT_ATTRIBUTES": ",W,10,",
        "HDSD": "132",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "63.2",
        "TMAX": "71",
        "TMIN": "55.4"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2017-11",
        "CDSD": "1142",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "24",
        "EMNT_ATTRIBUTES": ",W,11,",
        "EMXT": "73",
        "EMXT_ATTRIBUTES": ",W,03,",
        "HDSD": "700",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "46.1",
        "TMAX": "54",
        "TMIN": "38.2"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2017-12",
        "CDSD": "1142",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "9",
        "EMNT_ATTRIBUTES": ",W,31,",
        "EMXT": "58",
        "EMXT_ATTRIBUTES": ",W,05,",
        "HDSD": "1628",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "35.1",
        "TMAX": "40.5",
        "TMIN": "29.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2018-01",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "4",
        "EMNT_ATTRIBUTES": ",W,07,",
        "EMXT": "54",
        "EMXT_ATTRIBUTES": ",W,23,+",
        "HDSD": "2704",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "30.3",
        "TMAX": "37.5",
        "TMIN": "23.1"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2018-02",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "16",
        "EMNT_ATTRIBUTES": ",W,03,",
        "EMXT": "65",
        "EMXT_ATTRIBUTES": ",W,21,",
        "HDSD": "3408",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "39.8",
        "TMAX": "47.2",
        "TMIN": "32.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2018-03",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "27",
        "EMNT_ATTRIBUTES": ",W,17,",
        "EMXT": "62",
        "EMXT_ATTRIBUTES": ",W,30,",
        "HDSD": "4203",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "39.4",
        "TMAX": "45.8",
        "TMIN": "33"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2018-04",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "30",
        "EMNT_ATTRIBUTES": ",W,09,",
        "EMXT": "70",
        "EMXT_ATTRIBUTES": ",W,13,",
        "HDSD": "4742",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "47",
        "TMAX": "54.5",
        "TMIN": "39.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2018-05",
        "CDSD": "51",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "47",
        "EMNT_ATTRIBUTES": ",W,01,",
        "EMXT": "84",
        "EMXT_ATTRIBUTES": ",W,03,",
        "HDSD": "4843",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "63.4",
        "TMAX": "71.3",
        "TMIN": "55.4"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2018-06",
        "CDSD": "208",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "51",
        "EMNT_ATTRIBUTES": ",W,04,+",
        "EMXT": "91",
        "EMXT_ATTRIBUTES": ",W,29,",
        "HDSD": "4867",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "69.5",
        "TMAX": "76.9",
        "TMIN": "62"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2018-07",
        "CDSD": "561",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "59",
        "EMNT_ATTRIBUTES": ",W,08,",
        "EMXT": "94",
        "EMXT_ATTRIBUTES": ",W,01,",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "76.4",
        "TMAX": "83.4",
        "TMIN": "69.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2018-08",
        "CDSD": "947",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "62",
        "EMNT_ATTRIBUTES": ",W,24,",
        "EMXT": "92",
        "EMXT_ATTRIBUTES": ",W,30,+",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "77.4",
        "TMAX": "83.9",
        "TMIN": "71"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2018-09",
        "CDSD": "1135",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "54",
        "EMNT_ATTRIBUTES": ",W,30,",
        "EMXT": "93",
        "EMXT_ATTRIBUTES": ",W,04,",
        "HDSD": "19",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "70.6",
        "TMAX": "76.7",
        "TMIN": "64.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2018-10",
        "CDSD": "1185",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "36",
        "EMNT_ATTRIBUTES": ",W,26,",
        "EMXT": "80",
        "EMXT_ATTRIBUTES": ",W,07,",
        "HDSD": "290",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "57.9",
        "TMAX": "64.3",
        "TMIN": "51.4"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2018-11",
        "CDSD": "1185",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "15",
        "EMNT_ATTRIBUTES": ",W,23,",
        "EMXT": "66",
        "EMXT_ATTRIBUTES": ",W,02,+",
        "HDSD": "910",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "44.3",
        "TMAX": "50.5",
        "TMIN": "38.1"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2018-12",
        "CDSD": "1185",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "24",
        "EMNT_ATTRIBUTES": ",W,19,+",
        "EMXT": "57",
        "EMXT_ATTRIBUTES": ",W,21,",
        "HDSD": "1689",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "39.9",
        "TMAX": "45.6",
        "TMIN": "34.1"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2019-01",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "3",
        "EMNT_ATTRIBUTES": ",W,31,",
        "EMXT": "59",
        "EMXT_ATTRIBUTES": ",W,01,",
        "HDSD": "2697",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "32.5",
        "TMAX": "39.4",
        "TMIN": "25.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2019-02",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "11",
        "EMNT_ATTRIBUTES": ",W,01,",
        "EMXT": "60",
        "EMXT_ATTRIBUTES": ",W,05,",
        "HDSD": "3526",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "35.4",
        "TMAX": "42.1",
        "TMIN": "28.7"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2019-03",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "18",
        "EMNT_ATTRIBUTES": ",W,07,",
        "EMXT": "59",
        "EMXT_ATTRIBUTES": ",W,15,",
        "HDSD": "4298",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "40.1",
        "TMAX": "46.7",
        "TMIN": "33.4"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2019-04",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "31",
        "EMNT_ATTRIBUTES": ",W,02,",
        "EMXT": "70",
        "EMXT_ATTRIBUTES": ",W,24,+",
        "HDSD": "4669",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "52.6",
        "TMAX": "59.7",
        "TMIN": "45.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2019-05",
        "CDSD": "34",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "43",
        "EMNT_ATTRIBUTES": ",W,13,+",
        "EMXT": "86",
        "EMXT_ATTRIBUTES": ",W,20,",
        "HDSD": "4844",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "60.4",
        "TMAX": "67.4",
        "TMIN": "53.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2019-06",
        "CDSD": "212",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "55",
        "EMNT_ATTRIBUTES": ",W,15,+",
        "EMXT": "91",
        "EMXT_ATTRIBUTES": ",W,27,",
        "HDSD": "4852",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "70.7",
        "TMAX": "78.3",
        "TMIN": "63"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2019-07",
        "CDSD": "639",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "65",
        "EMNT_ATTRIBUTES": ",W,24,+",
        "EMXT": "99",
        "EMXT_ATTRIBUTES": ",W,21,+",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "78.8",
        "TMAX": "86.7",
        "TMIN": "70.8"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2019-08",
        "CDSD": "960",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "60",
        "EMNT_ATTRIBUTES": ",W,27,+",
        "EMXT": "89",
        "EMXT_ATTRIBUTES": ",W,22,+",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "75.3",
        "TMAX": "82.4",
        "TMIN": "68.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2019-09",
        "CDSD": "1102",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "49",
        "EMNT_ATTRIBUTES": ",W,19,",
        "EMXT": "84",
        "EMXT_ATTRIBUTES": ",W,11,",
        "HDSD": "11",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "69.3",
        "TMAX": "76.8",
        "TMIN": "61.9"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2019-10",
        "CDSD": "1124",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "40",
        "EMNT_ATTRIBUTES": ",W,19,",
        "EMXT": "95",
        "EMXT_ATTRIBUTES": ",W,02,",
        "HDSD": "205",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "59.5",
        "TMAX": "66.5",
        "TMIN": "52.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2019-11",
        "CDSD": "1124",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "23",
        "EMNT_ATTRIBUTES": ",W,13,",
        "EMXT": "68",
        "EMXT_ATTRIBUTES": ",W,01,",
        "HDSD": "856",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "43.3",
        "TMAX": "50.6",
        "TMIN": "36"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2019-12",
        "CDSD": "1124",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "17",
        "EMNT_ATTRIBUTES": ",W,19,",
        "EMXT": "57",
        "EMXT_ATTRIBUTES": ",W,10,",
        "HDSD": "1690",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "38.1",
        "TMAX": "44.1",
        "TMIN": "32.1"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2020-01",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "19",
        "EMNT_ATTRIBUTES": ",W,21,",
        "EMXT": "68",
        "EMXT_ATTRIBUTES": ",W,12,",
        "HDSD": "2505",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "38.7",
        "TMAX": "45.4",
        "TMIN": "32"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2020-02",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "14",
        "EMNT_ATTRIBUTES": ",W,15,",
        "EMXT": "55",
        "EMXT_ATTRIBUTES": ",W,03,",
        "HDSD": "3248",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "39.4",
        "TMAX": "46.2",
        "TMIN": "32.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2020-03",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "25",
        "EMNT_ATTRIBUTES": ",W,01,",
        "EMXT": "73",
        "EMXT_ATTRIBUTES": ",W,20,",
        "HDSD": "3822",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "46.5",
        "TMAX": "54",
        "TMIN": "38.9"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2020-04",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "34",
        "EMNT_ATTRIBUTES": ",W,12,",
        "EMXT": "66",
        "EMXT_ATTRIBUTES": ",W,13,",
        "HDSD": "4315",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "48.6",
        "TMAX": "55.9",
        "TMIN": "41.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2020-05",
        "CDSD": "13",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "34",
        "EMNT_ATTRIBUTES": ",W,09,",
        "EMXT": "83",
        "EMXT_ATTRIBUTES": ",W,30,",
        "HDSD": "4538",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "58.2",
        "TMAX": "67.1",
        "TMIN": "49.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2020-06",
        "CDSD": "213",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "51",
        "EMNT_ATTRIBUTES": ",W,01,",
        "EMXT": "89",
        "EMXT_ATTRIBUTES": ",W,29,",
        "HDSD": "4545",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "71.5",
        "TMAX": "80",
        "TMIN": "62.9"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2020-07",
        "CDSD": "656",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "65",
        "EMNT_ATTRIBUTES": ",W,02,",
        "EMXT": "97",
        "EMXT_ATTRIBUTES": ",W,20,",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "79.3",
        "TMAX": "86.4",
        "TMIN": "72.2"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2020-08",
        "CDSD": "1005",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "60",
        "EMNT_ATTRIBUTES": ",W,31,",
        "EMXT": "92",
        "EMXT_ATTRIBUTES": ",W,27,+",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "76.3",
        "TMAX": "83.1",
        "TMIN": "69.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2020-09",
        "CDSD": "1141",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "46",
        "EMNT_ATTRIBUTES": ",W,21,",
        "EMXT": "88",
        "EMXT_ATTRIBUTES": ",W,04,",
        "HDSD": "35",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "68.4",
        "TMAX": "75.8",
        "TMIN": "60.9"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2020-10",
        "CDSD": "1147",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "32",
        "EMNT_ATTRIBUTES": ",W,31,",
        "EMXT": "78",
        "EMXT_ATTRIBUTES": ",W,07,",
        "HDSD": "252",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "58.2",
        "TMAX": "64.9",
        "TMIN": "51.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2020-11",
        "CDSD": "1147",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "26",
        "EMNT_ATTRIBUTES": ",W,19,",
        "EMXT": "74",
        "EMXT_ATTRIBUTES": ",W,09,+",
        "HDSD": "676",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "50.9",
        "TMAX": "59.4",
        "TMIN": "42.4"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2020-12",
        "CDSD": "1147",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "18",
        "EMNT_ATTRIBUTES": ",W,19,",
        "EMXT": "61",
        "EMXT_ATTRIBUTES": ",W,13,",
        "HDSD": "1497",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "38.5",
        "TMAX": "44.7",
        "TMIN": "32.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2021-01",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "15",
        "EMNT_ATTRIBUTES": ",W,30,",
        "EMXT": "53",
        "EMXT_ATTRIBUTES": ",W,02,",
        "HDSD": "2433",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "34.8",
        "TMAX": "41.1",
        "TMIN": "28.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2021-02",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "17",
        "EMNT_ATTRIBUTES": ",W,08,",
        "EMXT": "52",
        "EMXT_ATTRIBUTES": ",W,27,",
        "HDSD": "3322",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "33.2",
        "TMAX": "38.3",
        "TMIN": "28.2"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2021-03",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "22",
        "EMNT_ATTRIBUTES": ",W,02,",
        "EMXT": "81",
        "EMXT_ATTRIBUTES": ",W,26,",
        "HDSD": "3973",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "44",
        "TMAX": "52.7",
        "TMIN": "35.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2021-04",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "29",
        "EMNT_ATTRIBUTES": ",W,02,",
        "EMXT": "73",
        "EMXT_ATTRIBUTES": ",W,28,",
        "HDSD": "4365",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "51.9",
        "TMAX": "60.5",
        "TMIN": "43.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2021-05",
        "CDSD": "48",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "42",
        "EMNT_ATTRIBUTES": ",W,01,",
        "EMXT": "94",
        "EMXT_ATTRIBUTES": ",W,22,",
        "HDSD": "4530",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "61.2",
        "TMAX": "70.4",
        "TMIN": "52.1"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2021-06",
        "CDSD": "245",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "52",
        "EMNT_ATTRIBUTES": ",W,01,",
        "EMXT": "91",
        "EMXT_ATTRIBUTES": ",W,30,+",
        "HDSD": "4534",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "71.4",
        "TMAX": "79.8",
        "TMIN": "63"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2021-07",
        "CDSD": "581",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "59",
        "EMNT_ATTRIBUTES": ",W,31,+",
        "EMXT": "90",
        "EMXT_ATTRIBUTES": ",W,26,",
        "HDSD": "1",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "75.8",
        "TMAX": "83",
        "TMIN": "68.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2021-08",
        "CDSD": "950",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "62",
        "EMNT_ATTRIBUTES": ",W,02,",
        "EMXT": "93",
        "EMXT_ATTRIBUTES": ",W,27,",
        "HDSD": "1",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "76.9",
        "TMAX": "83.4",
        "TMIN": "70.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2021-09",
        "CDSD": "1129",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "54",
        "EMNT_ATTRIBUTES": ",W,30,+",
        "EMXT": "87",
        "EMXT_ATTRIBUTES": ",W,13,",
        "HDSD": "8",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "70.7",
        "TMAX": "78",
        "TMIN": "63.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2021-10",
        "CDSD": "1162",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "47",
        "EMNT_ATTRIBUTES": ",W,29,+",
        "EMXT": "80",
        "EMXT_ATTRIBUTES": ",W,14,",
        "HDSD": "102",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "63",
        "TMAX": "69.9",
        "TMIN": "56.2"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2021-11",
        "CDSD": "1162",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "30",
        "EMNT_ATTRIBUTES": ",W,30,+",
        "EMXT": "69",
        "EMXT_ATTRIBUTES": ",W,09,",
        "HDSD": "663",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "46.3",
        "TMAX": "54.2",
        "TMIN": "38.4"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2021-12",
        "CDSD": "1162",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "24",
        "EMNT_ATTRIBUTES": ",W,20,",
        "EMXT": "61",
        "EMXT_ATTRIBUTES": ",W,17,+",
        "HDSD": "1333",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "43.4",
        "TMAX": "49.3",
        "TMIN": "37.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2022-01",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "9",
        "EMNT_ATTRIBUTES": ",W,16,",
        "EMXT": "59",
        "EMXT_ATTRIBUTES": ",W,02,",
        "HDSD": "2406",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "30.4",
        "TMAX": "38.1",
        "TMIN": "22.7"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2022-02",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "15",
        "EMNT_ATTRIBUTES": ",W,06,",
        "EMXT": "69",
        "EMXT_ATTRIBUTES": ",W,23,",
        "HDSD": "3226",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "35.7",
        "TMAX": "44.2",
        "TMIN": "27.2"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2022-03",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "19",
        "EMNT_ATTRIBUTES": ",W,04,",
        "EMXT": "63",
        "EMXT_ATTRIBUTES": ",W,21,+",
        "HDSD": "3896",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "43.4",
        "TMAX": "51.1",
        "TMIN": "35.7"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2022-04",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "37",
        "EMNT_ATTRIBUTES": ",W,18,",
        "EMXT": "72",
        "EMXT_ATTRIBUTES": ",W,12,",
        "HDSD": "4318",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "50.9",
        "TMAX": "58.5",
        "TMIN": "43.4"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2022-05",
        "CDSD": "52",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "42",
        "EMNT_ATTRIBUTES": ",W,01,",
        "EMXT": "94",
        "EMXT_ATTRIBUTES": ",W,31,",
        "HDSD": "4455",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "62.2",
        "TMAX": "70.4",
        "TMIN": "54.1"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2022-06",
        "CDSD": "213",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "55",
        "EMNT_ATTRIBUTES": ",W,19,",
        "EMXT": "94",
        "EMXT_ATTRIBUTES": ",W,17,",
        "HDSD": "4458",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "70.3",
        "TMAX": "78.1",
        "TMIN": "62.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2022-07",
        "CDSD": "656",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "65",
        "EMNT_ATTRIBUTES": ",W,11,+",
        "EMXT": "96",
        "EMXT_ATTRIBUTES": ",W,24,+",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "79.3",
        "TMAX": "86.9",
        "TMIN": "71.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2022-08",
        "CDSD": "1081",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "63",
        "EMNT_ATTRIBUTES": ",W,16,",
        "EMXT": "93",
        "EMXT_ATTRIBUTES": ",W,09,",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "78.7",
        "TMAX": "86.4",
        "TMIN": "71"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2022-09",
        "CDSD": "1262",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "49",
        "EMNT_ATTRIBUTES": ",W,24,",
        "EMXT": "89",
        "EMXT_ATTRIBUTES": ",W,01,",
        "HDSD": "21",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "70.3",
        "TMAX": "78",
        "TMIN": "62.7"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2022-10",
        "CDSD": "1266",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "38",
        "EMNT_ATTRIBUTES": ",W,30,",
        "EMXT": "76",
        "EMXT_ATTRIBUTES": ",W,07,+",
        "HDSD": "270",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "57.1",
        "TMAX": "64.5",
        "TMIN": "49.7"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2022-11",
        "CDSD": "1273",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "28",
        "EMNT_ATTRIBUTES": ",W,21,",
        "EMXT": "80",
        "EMXT_ATTRIBUTES": ",W,07,",
        "HDSD": "719",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "50.3",
        "TMAX": "57.8",
        "TMIN": "42.7"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2022-12",
        "CDSD": "1273",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "7",
        "EMNT_ATTRIBUTES": ",W,24,",
        "EMXT": "57",
        "EMXT_ATTRIBUTES": ",W,07,+",
        "HDSD": "1571",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "37.5",
        "TMAX": "44.1",
        "TMIN": "31"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2023-01",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "29",
        "EMNT_ATTRIBUTES": ",W,16,+",
        "EMXT": "61",
        "EMXT_ATTRIBUTES": ",W,04,",
        "HDSD": "2291",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "41.8",
        "TMAX": "47.6",
        "TMIN": "36"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2023-02",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "4",
        "EMNT_ATTRIBUTES": ",W,04,",
        "EMXT": "64",
        "EMXT_ATTRIBUTES": ",W,16,",
        "HDSD": "3023",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "38.9",
        "TMAX": "47",
        "TMIN": "30.8"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2023-03",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "29",
        "EMNT_ATTRIBUTES": ",W,31,+",
        "EMXT": "62",
        "EMXT_ATTRIBUTES": ",W,26,",
        "HDSD": "3714",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "42.7",
        "TMAX": "50.1",
        "TMIN": "35.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2023-04",
        "CDSD": "13",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "33",
        "EMNT_ATTRIBUTES": ",W,03,",
        "EMXT": "85",
        "EMXT_ATTRIBUTES": ",W,13,",
        "HDSD": "4045",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "54.4",
        "TMAX": "62.5",
        "TMIN": "46.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2023-05",
        "CDSD": "29",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "42",
        "EMNT_ATTRIBUTES": ",W,18,",
        "EMXT": "83",
        "EMXT_ATTRIBUTES": ",W,12,",
        "HDSD": "4217",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "60",
        "TMAX": "68.8",
        "TMIN": "51.2"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2023-06",
        "CDSD": "153",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "49",
        "EMNT_ATTRIBUTES": ",W,04,",
        "EMXT": "83",
        "EMXT_ATTRIBUTES": ",W,30,+",
        "HDSD": "4232",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "68.6",
        "TMAX": "76.7",
        "TMIN": "60.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2023-07",
        "CDSD": "550",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "64",
        "EMNT_ATTRIBUTES": ",W,31,",
        "EMXT": "92",
        "EMXT_ATTRIBUTES": ",W,27,",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "77.8",
        "TMAX": "84.8",
        "TMIN": "70.8"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2023-08",
        "CDSD": "832",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "62",
        "EMNT_ATTRIBUTES": ",W,02,",
        "EMXT": "89",
        "EMXT_ATTRIBUTES": ",W,13,",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "74.1",
        "TMAX": "80.8",
        "TMIN": "67.4"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2023-09",
        "CDSD": "1003",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "51",
        "EMNT_ATTRIBUTES": ",W,27,",
        "EMXT": "93",
        "EMXT_ATTRIBUTES": ",W,06,+",
        "HDSD": "40",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "69.4",
        "TMAX": "76.2",
        "TMIN": "62.5"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2023-10",
        "CDSD": "1023",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "43",
        "EMNT_ATTRIBUTES": ",W,24,",
        "EMXT": "81",
        "EMXT_ATTRIBUTES": ",W,28,",
        "HDSD": "225",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "59.7",
        "TMAX": "67",
        "TMIN": "52.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2023-11",
        "CDSD": "1023",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "26",
        "EMNT_ATTRIBUTES": ",W,29,",
        "EMXT": "65",
        "EMXT_ATTRIBUTES": ",W,05,",
        "HDSD": "816",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "45.3",
        "TMAX": "53",
        "TMIN": "37.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2023-12",
        "CDSD": "1023",
        "CDSD_ATTRIBUTES": "W",
        "EMNT": "25",
        "EMNT_ATTRIBUTES": ",W,22,",
        "EMXT": "59",
        "EMXT_ATTRIBUTES": ",W,18,",
        "HDSD": "1509",
        "HDSD_ATTRIBUTES": "W",
        "TAVG": "42.7",
        "TMAX": "48.5",
        "TMIN": "36.8"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2024-01",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "",
        "EMNT": "18",
        "EMNT_ATTRIBUTES": ",W,20,+",
        "EMXT": "56",
        "EMXT_ATTRIBUTES": ",W,13,",
        "HDSD": "2406",
        "HDSD_ATTRIBUTES": "",
        "TAVG": "36",
        "TMAX": "41.3",
        "TMIN": "30.8"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2024-02",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "",
        "EMNT": "21",
        "EMNT_ATTRIBUTES": ",W,25,",
        "EMXT": "56",
        "EMXT_ATTRIBUTES": ",W,28,",
        "HDSD": "3195",
        "HDSD_ATTRIBUTES": "",
        "TAVG": "37.8",
        "TMAX": "44",
        "TMIN": "31.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2024-03",
        "CDSD": "0",
        "CDSD_ATTRIBUTES": "",
        "EMNT": "28",
        "EMNT_ATTRIBUTES": ",W,22,+",
        "EMXT": "72",
        "EMXT_ATTRIBUTES": ",W,15,",
        "HDSD": "3756",
        "HDSD_ATTRIBUTES": "",
        "TAVG": "46.9",
        "TMAX": "54.5",
        "TMIN": "39.3"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2024-04",
        "CDSD": "5",
        "CDSD_ATTRIBUTES": "",
        "EMNT": "37",
        "EMNT_ATTRIBUTES": ",W,26,+",
        "EMXT": "82",
        "EMXT_ATTRIBUTES": ",W,29,",
        "HDSD": "4134",
        "HDSD_ATTRIBUTES": "",
        "TAVG": "52.6",
        "TMAX": "60.1",
        "TMIN": "45"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2024-05",
        "CDSD": "56",
        "CDSD_ATTRIBUTES": "",
        "EMNT": "47",
        "EMNT_ATTRIBUTES": ",W,11,",
        "EMXT": "85",
        "EMXT_ATTRIBUTES": ",W,24,",
        "HDSD": "4246",
        "HDSD_ATTRIBUTES": "",
        "TAVG": "63",
        "TMAX": "70.5",
        "TMIN": "55.6"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2024-06",
        "CDSD": "320",
        "CDSD_ATTRIBUTES": "",
        "EMNT": "60",
        "EMNT_ATTRIBUTES": ",W,11,",
        "EMXT": "91",
        "EMXT_ATTRIBUTES": ",W,25,+",
        "HDSD": "4246",
        "HDSD_ATTRIBUTES": "",
        "TAVG": "73.8",
        "TMAX": "81.6",
        "TMIN": "65.9"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2024-07",
        "CDSD": "718",
        "CDSD_ATTRIBUTES": "",
        "EMNT": "64",
        "EMNT_ATTRIBUTES": ",W,03,+",
        "EMXT": "91",
        "EMXT_ATTRIBUTES": ",W,31,",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "",
        "TAVG": "77.8",
        "TMAX": "84.5",
        "TMIN": "71.1"
    },
    {
        "\ufeffSTATION": "USW00094789",
        "NAME": "JFK INTERNATIONAL AIRPORT, NY US",
        "LATITUDE": "40.63915",
        "LONGITUDE": "-73.7639",
        "ELEVATION": "2.7",
        "DATE": "2024-08",
        "CDSD": "1056",
        "CDSD_ATTRIBUTES": "",
        "EMNT": "58",
        "EMNT_ATTRIBUTES": ",W,21,",
        "EMXT": "95",
        "EMXT_ATTRIBUTES": ",W,28,",
        "HDSD": "0",
        "HDSD_ATTRIBUTES": "",
        "TAVG": "75.9",
        "TMAX": "83.4",
        "TMIN": "68.4"
    }
]