var utility_data = [
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "McCarthy House",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "4218",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "McCarthy House",
        "Commodity": "Oil #2",
        "Units": "GAL",
        "SerialNumber": "UME_314196_MH",
        "AccountNumber": "314196",
        "Vendor": "United Metro Energy",
        "BillStartDate": "2022-01-13 00:00:00",
        "BillEndDate": "2022-02-07 00:00:00",
        "Year": "2022",
        "Month": "1",
        "BillDays": "25",
        "TotalConsumption": "422.2",
        "TotalCost": "1279.54",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Riland",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "82152",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "NRG_420032-7976",
        "Commodity": "Natural Gas",
        "Units": "THERM",
        "SerialNumber": "420032-7976",
        "AccountNumber": "62918-27002-004658759",
        "Vendor": "NRG",
        "BillStartDate": "2023-11-16 00:00:00",
        "BillEndDate": "2023-12-19 00:00:00",
        "Year": "2023",
        "Month": "11",
        "BillDays": "33",
        "TotalConsumption": "0",
        "TotalCost": "43.82",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Field House",
        "PrimaryUse": "Other",
        "BuildingSizeSQFT": "17200",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "Locker Room",
        "Commodity": "Water & Sewer",
        "Units": "KGAL",
        "SerialNumber": "01-002450.00",
        "AccountNumber": "01-002450.00",
        "Vendor": "Old Westbury Water",
        "BillStartDate": "2022-11-01 00:00:00",
        "BillEndDate": "2023-05-01 00:00:00",
        "Year": "2022",
        "Month": "11",
        "BillDays": "181",
        "TotalConsumption": "0",
        "TotalCost": "185",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "North House",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "1816",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Brookville",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "NG_50442-99000",
        "Commodity": "Natural Gas",
        "Units": "THERM",
        "SerialNumber": "4698796",
        "AccountNumber": "50442-99000",
        "Vendor": "National Grid",
        "BillStartDate": "2023-11-16 00:00:00",
        "BillEndDate": "2023-12-20 00:00:00",
        "Year": "2023",
        "Month": "11",
        "BillDays": "34",
        "TotalConsumption": "196",
        "TotalCost": "301.3",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "De Seversky Mansion",
        "PrimaryUse": "Other",
        "BuildingSizeSQFT": "25710",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Brookville",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "Kitchen",
        "Commodity": "Oil #2",
        "Units": "GAL",
        "SerialNumber": "UME_314196_Kitchen",
        "AccountNumber": "314196",
        "Vendor": "United Metro Energy",
        "BillStartDate": "2022-04-11 00:00:00",
        "BillEndDate": "2022-04-18 00:00:00",
        "Year": "2022",
        "Month": "4",
        "BillDays": "7",
        "TotalConsumption": "215.3",
        "TotalCost": "886.25",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "New York City Campus",
        "BuildingName": "33 West 60th Street",
        "PrimaryUse": "Other",
        "BuildingSizeSQFT": "7664",
        "AddressStreet": "33 West 60th Street",
        "AddressCity": "New York",
        "AddressState": "NY",
        "AddressZipCode": "10023",
        "MeterName": "3rd Floor",
        "Commodity": "Electric",
        "Units": "KWH",
        "SerialNumber": "16604-35000-5",
        "AccountNumber": "16604-35000-5",
        "Vendor": "ConEd",
        "BillStartDate": "2023-12-21 00:00:00",
        "BillEndDate": "2024-01-23 00:00:00",
        "Year": "2023",
        "Month": "12",
        "BillDays": "33",
        "TotalConsumption": "1958",
        "TotalCost": "564.16",
        "ActualDemand": "12.26",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "McCarthy House",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "4218",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "McCarthy House",
        "Commodity": "Oil #2",
        "Units": "GAL",
        "SerialNumber": "UME_314196_MH",
        "AccountNumber": "314196",
        "Vendor": "United Metro Energy",
        "BillStartDate": "2021-12-13 00:00:00",
        "BillEndDate": "2021-12-27 00:00:00",
        "Year": "2021",
        "Month": "12",
        "BillDays": "14",
        "TotalConsumption": "184.7",
        "TotalCost": "469.12",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Serota",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "48775",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "NG_37970-76006",
        "Commodity": "Natural Gas",
        "Units": "THERM",
        "SerialNumber": "6027686",
        "AccountNumber": "37970-76006",
        "Vendor": "National Grid",
        "BillStartDate": "2023-11-16 00:00:00",
        "BillEndDate": "2023-12-20 00:00:00",
        "Year": "2023",
        "Month": "11",
        "BillDays": "34",
        "TotalConsumption": "1662",
        "TotalCost": "1205.48",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Main Meters",
        "PrimaryUse": "Other",
        "BuildingSizeSQFT": "142859",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "Sign",
        "Commodity": "Electric",
        "Units": "KWH",
        "SerialNumber": "4889666123",
        "AccountNumber": "4889666123",
        "Vendor": "PSEG",
        "BillStartDate": "2022-06-30 00:00:00",
        "BillEndDate": "2022-07-31 00:00:00",
        "Year": "2022",
        "Month": "6",
        "BillDays": "31",
        "TotalConsumption": "111",
        "TotalCost": "64.4",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Main Meters",
        "PrimaryUse": "Other",
        "BuildingSizeSQFT": "142859",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "Sign",
        "Commodity": "Electric",
        "Units": "KWH",
        "SerialNumber": "4889666123",
        "AccountNumber": "4889666123",
        "Vendor": "PSEG",
        "BillStartDate": "2024-01-31 00:00:00",
        "BillEndDate": "2024-02-29 00:00:00",
        "Year": "2024",
        "Month": "1",
        "BillDays": "29",
        "TotalConsumption": "104",
        "TotalCost": "60.47",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Gerry House",
        "PrimaryUse": "Administration Office",
        "BuildingSizeSQFT": "14657",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "NG_37970-74002",
        "Commodity": "Natural Gas",
        "Units": "THERM",
        "SerialNumber": "7350551",
        "AccountNumber": "37970-74002",
        "Vendor": "National Grid",
        "BillStartDate": "2023-03-22 00:00:00",
        "BillEndDate": "2023-04-20 00:00:00",
        "Year": "2023",
        "Month": "3",
        "BillDays": "29",
        "TotalConsumption": "813",
        "TotalCost": "710.82",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Simonson House",
        "PrimaryUse": "Facility Services",
        "BuildingSizeSQFT": "6084",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "JWD_25815400-0",
        "Commodity": "Water",
        "Units": "KGAL",
        "SerialNumber": "JWD_25815400-0",
        "AccountNumber": "25815400-0",
        "Vendor": "Jericho Water District",
        "BillStartDate": "2023-02-07 00:00:00",
        "BillEndDate": "2023-05-03 00:00:00",
        "Year": "2023",
        "Month": "2",
        "BillDays": "85",
        "TotalConsumption": "15",
        "TotalCost": "19.05",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Gerry House",
        "PrimaryUse": "Administration Office",
        "BuildingSizeSQFT": "14657",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "NG_37970-74002",
        "Commodity": "Natural Gas",
        "Units": "THERM",
        "SerialNumber": "7350551",
        "AccountNumber": "37970-74002",
        "Vendor": "National Grid",
        "BillStartDate": "2022-12-19 00:00:00",
        "BillEndDate": "2023-01-19 00:00:00",
        "Year": "2022",
        "Month": "12",
        "BillDays": "31",
        "TotalConsumption": "1776",
        "TotalCost": "1212.15",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "500 Building",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "19749",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "NRG_420032-7964",
        "Commodity": "Natural Gas",
        "Units": "THERM",
        "SerialNumber": "420032-7964",
        "AccountNumber": "80230-31001-000730790",
        "Vendor": "NRG",
        "BillStartDate": "2022-06-08 00:00:00",
        "BillEndDate": "2022-07-08 00:00:00",
        "Year": "2022",
        "Month": "6",
        "BillDays": "30",
        "TotalConsumption": "0",
        "TotalCost": "0",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Balding House",
        "PrimaryUse": "Other",
        "BuildingSizeSQFT": "6858",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "PSEG_5959875251",
        "Commodity": "Electric",
        "Units": "KWH",
        "SerialNumber": "5959875251",
        "AccountNumber": "5959875251",
        "Vendor": "PSEG",
        "BillStartDate": "2024-01-02 00:00:00",
        "BillEndDate": "2024-01-31 00:00:00",
        "Year": "2024",
        "Month": "1",
        "BillDays": "29",
        "TotalConsumption": "1487",
        "TotalCost": "426.74",
        "ActualDemand": "6.5",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "500 Building",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "19749",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "PSEG_5959885001",
        "Commodity": "Electric",
        "Units": "KWH",
        "SerialNumber": "96767553",
        "AccountNumber": "5959885001",
        "Vendor": "PSEG",
        "BillStartDate": "2022-05-02 00:00:00",
        "BillEndDate": "2022-06-02 00:00:00",
        "Year": "2022",
        "Month": "5",
        "BillDays": "31",
        "TotalConsumption": "104",
        "TotalCost": "38.84",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "New York City Campus",
        "BuildingName": "1855 Broadway",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "97303",
        "AddressStreet": "1855 Broadway",
        "AddressCity": "New York",
        "AddressState": "NY",
        "AddressZipCode": "10023",
        "MeterName": "NRG_420032-82343",
        "Commodity": "Natural Gas",
        "Units": "THERM",
        "SerialNumber": "420032-82343",
        "AccountNumber": "66397540007-3437745",
        "Vendor": "NRG",
        "BillStartDate": "2022-01-26 00:00:00",
        "BillEndDate": "2022-02-25 00:00:00",
        "Year": "2022",
        "Month": "1",
        "BillDays": "30",
        "TotalConsumption": "0",
        "TotalCost": "0",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "New York City Campus",
        "BuildingName": "33 West 60th Street",
        "PrimaryUse": "Other",
        "BuildingSizeSQFT": "7664",
        "AddressStreet": "33 West 60th Street",
        "AddressCity": "New York",
        "AddressState": "NY",
        "AddressZipCode": "10023",
        "MeterName": "3rd Floor",
        "Commodity": "Electric",
        "Units": "KWH",
        "SerialNumber": "16604-35000-5",
        "AccountNumber": "16604-35000-5",
        "Vendor": "ConEd",
        "BillStartDate": "2022-08-23 00:00:00",
        "BillEndDate": "2022-09-22 00:00:00",
        "Year": "2022",
        "Month": "8",
        "BillDays": "30",
        "TotalConsumption": "1782",
        "TotalCost": "500.41",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Gerry House",
        "PrimaryUse": "Administration Office",
        "BuildingSizeSQFT": "14657",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "NG_37970-74002",
        "Commodity": "Natural Gas",
        "Units": "THERM",
        "SerialNumber": "7350551",
        "AccountNumber": "37970-74002",
        "Vendor": "National Grid",
        "BillStartDate": "2024-02-20 00:00:00",
        "BillEndDate": "2024-03-18 00:00:00",
        "Year": "2024",
        "Month": "2",
        "BillDays": "27",
        "TotalConsumption": "1087",
        "TotalCost": "917.72",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "New York City Campus",
        "BuildingName": "26 West 61st Street",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "46771",
        "AddressStreet": "26 West 61st Street",
        "AddressCity": "New York",
        "AddressState": "NY",
        "AddressZipCode": "10023",
        "MeterName": "EPG_27925450002",
        "Commodity": "Electric",
        "Units": "KWH",
        "SerialNumber": "EPG_27925450002",
        "AccountNumber": "27925450002",
        "Vendor": "Engie Power and Gas",
        "BillStartDate": "2021-11-23 00:00:00",
        "BillEndDate": "2021-12-23 00:00:00",
        "Year": "2021",
        "Month": "11",
        "BillDays": "30",
        "TotalConsumption": "0",
        "TotalCost": "810.94",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Midge Karr",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "21438",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "NG_42881-51006",
        "Commodity": "Natural Gas",
        "Units": "THERM",
        "SerialNumber": "4583122",
        "AccountNumber": "42881-51006",
        "Vendor": "National Grid",
        "BillStartDate": "2023-04-20 00:00:00",
        "BillEndDate": "2023-05-19 00:00:00",
        "Year": "2023",
        "Month": "4",
        "BillDays": "29",
        "TotalConsumption": "38",
        "TotalCost": "101.04",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Wisser Memorial Library",
        "PrimaryUse": "Other",
        "BuildingSizeSQFT": "35842",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "NG_75384-42006",
        "Commodity": "Natural Gas",
        "Units": "THERM",
        "SerialNumber": "1358168",
        "AccountNumber": "75384-42006",
        "Vendor": "National Grid",
        "BillStartDate": "2023-01-18 00:00:00",
        "BillEndDate": "2023-02-15 00:00:00",
        "Year": "2023",
        "Month": "1",
        "BillDays": "28",
        "TotalConsumption": "1992",
        "TotalCost": "1424.81",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "North House",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "1816",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Brookville",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "NRG_420032-7975",
        "Commodity": "Natural Gas",
        "Units": "THERM",
        "SerialNumber": "420032-7975",
        "AccountNumber": "50442-99000-004698796",
        "Vendor": "NRG",
        "BillStartDate": "2024-01-22 00:00:00",
        "BillEndDate": "2024-02-20 00:00:00",
        "Year": "2024",
        "Month": "1",
        "BillDays": "29",
        "TotalConsumption": "0",
        "TotalCost": "114.14",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "New York City Campus",
        "BuildingName": "26 West 61st Street",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "46771",
        "AddressStreet": "26 West 61st Street",
        "AddressCity": "New York",
        "AddressState": "NY",
        "AddressZipCode": "10023",
        "MeterName": "CE_24441-55000-1",
        "Commodity": "Electric",
        "Units": "KWH",
        "SerialNumber": "11032132",
        "AccountNumber": "24441-55000-1",
        "Vendor": "ConEd",
        "BillStartDate": "2023-08-23 00:00:00",
        "BillEndDate": "2023-09-22 00:00:00",
        "Year": "2023",
        "Month": "8",
        "BillDays": "30",
        "TotalConsumption": "4446",
        "TotalCost": "770.99",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "Main Meters",
        "PrimaryUse": "Other",
        "BuildingSizeSQFT": "142859",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "Campus Main 2",
        "Commodity": "Electric",
        "Units": "KWH",
        "SerialNumber": "80338639",
        "AccountNumber": "4910504801",
        "Vendor": "PSEG",
        "BillStartDate": "2023-02-15 00:00:00",
        "BillEndDate": "2023-03-16 00:00:00",
        "Year": "2023",
        "Month": "2",
        "BillDays": "29",
        "TotalConsumption": "13500",
        "TotalCost": "2132.97",
        "ActualDemand": "26.1",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "New York City Campus",
        "BuildingName": "1855 Broadway",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "97303",
        "AddressStreet": "1855 Broadway",
        "AddressCity": "New York",
        "AddressState": "NY",
        "AddressZipCode": "10023",
        "MeterName": "Steam",
        "Commodity": "Steam",
        "Units": "MLB",
        "SerialNumber": "CE_6421000000",
        "AccountNumber": "6421000000",
        "Vendor": "ConEd",
        "BillStartDate": "2024-05-20 00:00:00",
        "BillEndDate": "2024-06-18 00:00:00",
        "Year": "2024",
        "Month": "5",
        "BillDays": "29",
        "TotalConsumption": "825.74",
        "TotalCost": "18791.94",
        "ActualDemand": "0",
        "BilledDemand": "14282.54",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "New York City Campus",
        "BuildingName": "1855 Broadway",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "97303",
        "AddressStreet": "1855 Broadway",
        "AddressCity": "New York",
        "AddressState": "NY",
        "AddressZipCode": "10023",
        "MeterName": "Fire Alarm",
        "Commodity": "Electric",
        "Units": "KWH",
        "SerialNumber": "34768-94000-8",
        "AccountNumber": "34768-94000-8",
        "Vendor": "ConEd",
        "BillStartDate": "2023-09-30 00:00:00",
        "BillEndDate": "2023-10-31 00:00:00",
        "Year": "2023",
        "Month": "9",
        "BillDays": "31",
        "TotalConsumption": "0",
        "TotalCost": "10.87",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "New York City Campus",
        "BuildingName": "26 West 61st Street",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "46771",
        "AddressStreet": "26 West 61st Street",
        "AddressCity": "New York",
        "AddressState": "NY",
        "AddressZipCode": "10023",
        "MeterName": "EPG_99770240002",
        "Commodity": "Electric",
        "Units": "KWH",
        "SerialNumber": "EPG_99770240002",
        "AccountNumber": "99770240002",
        "Vendor": "Engie Power and Gas",
        "BillStartDate": "2023-01-26 00:00:00",
        "BillEndDate": "2023-02-27 00:00:00",
        "Year": "2023",
        "Month": "1",
        "BillDays": "32",
        "TotalConsumption": "0",
        "TotalCost": "785.46",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "David G. Salten Hall",
        "PrimaryUse": "Class_Office-Large",
        "BuildingSizeSQFT": "22314",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Old Westbury",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "NRG_420032-7971",
        "Commodity": "Natural Gas",
        "Units": "THERM",
        "SerialNumber": "420032-7971",
        "AccountNumber": "62918-25008-001349470",
        "Vendor": "NRG",
        "BillStartDate": "2023-01-19 00:00:00",
        "BillEndDate": "2023-02-17 00:00:00",
        "Year": "2023",
        "Month": "1",
        "BillDays": "29",
        "TotalConsumption": "0",
        "TotalCost": "1288.85",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    },
    {
        "ProgramName": "New York Institute of Tech-NY",
        "ComplexName": "Long Island Campus",
        "BuildingName": "De Seversky Mansion",
        "PrimaryUse": "Other",
        "BuildingSizeSQFT": "25710",
        "AddressStreet": "Northern Boulevard",
        "AddressCity": "Brookville",
        "AddressState": "NY",
        "AddressZipCode": "11568",
        "MeterName": "Kitchen",
        "Commodity": "Oil #2",
        "Units": "GAL",
        "SerialNumber": "UME_314196_Kitchen",
        "AccountNumber": "314196",
        "Vendor": "United Metro Energy",
        "BillStartDate": "2022-01-27 00:00:00",
        "BillEndDate": "2022-01-31 00:00:00",
        "Year": "2022",
        "Month": "1",
        "BillDays": "4",
        "TotalConsumption": "543.2",
        "TotalCost": "1606.07",
        "ActualDemand": "0",
        "BilledDemand": "0",
        "DemandCharge": "0",
        "AccountLevelCharges": "0",
        "EstimatedBill": "FALSE",
        "AccountLevelCharges.1": "0",
        "EstimatedBill.1": "FALSE"
    }
];